#!/bin/bash
# install_usb_audio_optimize.sh
#
# For Qji: one-time setup for USB output digital-noise mitigation
# (run once, with sudo)
#
# What it does:
#   1) Detects connected USB audio devices and, for each one, creates a
#      udev rule (keyed on idVendor/idProduct) that disables USB
#      autosuspend
#      (prevents the clicks/brief dropouts caused by USB power-saving
#       switching the device on and off)
#   2) Grants the `audio` group realtime scheduling priority (rtprio)
#      and memory-lock (memlock) permissions
#      (prevents clicks caused by buffer underruns when the playback
#       process loses the CPU to another process)
#   3) Adds the invoking user to the `audio` group (if not already a member)
#
# Usage:
#   sudo bash install_usb_audio_optimize.sh
#   Log out and back in once afterward (so the group change takes effect).

set -e

if [ "$EUID" -ne 0 ]; then
    echo "❌ This script requires root. Please re-run it with sudo:"
    echo "   sudo bash $0"
    exit 1
fi

TARGET_USER="${SUDO_USER:-$(whoami)}"
echo "============================================================"
echo "🔌 Qji USB Audio Noise-Mitigation Setup"
echo "============================================================"

# ---------------------------------------------------------------
# 1) Detect connected USB audio devices and generate udev rules
# ---------------------------------------------------------------
RULE_FILE="/etc/udev/rules.d/99-qji-usb-audio-noautosuspend.rules"
echo "# Qji: disable autosuspend for USB audio output devices" > "$RULE_FILE"
echo "# (this file was auto-generated by install_usb_audio_optimize.sh)" >> "$RULE_FILE"

FOUND=0
for cardpath in /sys/class/sound/card*/device; do
    [ -e "$cardpath" ] || continue
    devpath=$(readlink -f "$cardpath")
    # Walk up the parent directories until idVendor/idProduct are found
    # (locates the actual USB device directory)
    d="$devpath"
    for _i in 1 2 3 4 5 6; do
        if [ -f "$d/idVendor" ] && [ -f "$d/idProduct" ]; then
            VID=$(cat "$d/idVendor")
            PID=$(cat "$d/idProduct")
            NAME=$(cat "$d/product" 2>/dev/null || echo "Unknown USB Audio Device")
            echo "  Found: $NAME (idVendor=$VID idProduct=$PID)"
            {
                echo "ACTION==\"add\", SUBSYSTEM==\"usb\", ATTR{idVendor}==\"$VID\", ATTR{idProduct}==\"$PID\", TEST==\"power/control\", ATTR{power/control}=\"on\""
                echo "ACTION==\"add\", SUBSYSTEM==\"usb\", ATTR{idVendor}==\"$VID\", ATTR{idProduct}==\"$PID\", TEST==\"power/autosuspend\", ATTR{power/autosuspend}=\"-1\""
                echo "ACTION==\"add\", SUBSYSTEM==\"usb\", ATTR{idVendor}==\"$VID\", ATTR{idProduct}==\"$PID\", RUN+=\"/bin/sh -c 'chgrp audio /sys\$devpath/power/control 2>/dev/null; chmod g+w /sys\$devpath/power/control 2>/dev/null; chgrp audio /sys\$devpath/power/autosuspend 2>/dev/null; chmod g+w /sys\$devpath/power/autosuspend 2>/dev/null'\""
            } >> "$RULE_FILE"
            FOUND=$((FOUND+1))
            break
        fi
        d=$(dirname "$d")
    done
done

if [ "$FOUND" -eq 0 ]; then
    echo "⚠️ No USB audio device found (connect your DAC, then re-run this script)"
else
    echo "✅ Created rules for ${FOUND} USB audio device(s): $RULE_FILE"
    udevadm control --reload-rules
    udevadm trigger --action=add --subsystem-match=usb
    echo "✅ Applied the udev rules"
fi

# ---------------------------------------------------------------
# 2) Grant the `audio` group rtprio/memlock permissions
# ---------------------------------------------------------------
LIMITS_FILE="/etc/security/limits.d/99-qji-audio-rt.conf"
cat > "$LIMITS_FILE" << 'EOF'
# Qji: realtime-priority settings for more stable audio playback
# (this file was auto-generated by install_usb_audio_optimize.sh)
@audio   -  rtprio     95
@audio   -  memlock    unlimited
@audio   -  nice       -19
EOF
echo "✅ Created the realtime-priority permission settings: $LIMITS_FILE"

# ---------------------------------------------------------------
# 3) Add the invoking user to the `audio` group
# ---------------------------------------------------------------
if id -nG "$TARGET_USER" | grep -qw audio; then
    echo "✅ User '$TARGET_USER' is already a member of the audio group"
else
    usermod -aG audio "$TARGET_USER"
    echo "✅ Added user '$TARGET_USER' to the audio group"
fi

echo "============================================================"
echo "🎉 Setup complete"
echo "============================================================"
echo "⚠️ Important: log out and back in once, so the group change takes effect"
echo "   (once applied, Qji will show \"✅ Realtime priority: available\" at startup)"
echo ""
echo "Note (optional, for advanced users):"
echo "  If you get dropouts with high-resolution material (DSD/PCM 768kHz, etc.),"
echo "  increasing the usbcore.usbfs_memory_mb kernel parameter may help."
echo "  e.g. add usbcore.usbfs_memory_mb=1000 to GRUB_CMDLINE_LINUX_DEFAULT,"
echo "  then run update-grub and reboot (not automated here — do this manually"
echo "  only if needed)."
